### ISSUE TITLE
[BUG] Same issues as #129 using rconfix release

### ISSUE THREAD

**Issue by sanegaming** [FlowingSPDG/get5loader#175]
**Where bugs related**
I am having the same issue as reported in #129 

**Describe the bug**
I have get5 + splewis apistats on the game server and the rcon-fix get5 binary and when attempting to create match I get "2020/06/20 23:16:11 JSON Unmarshal error: invalid character 'L' after top-level value
[GIN] 2020/06/20 - 23:16:11 | 500 |   27.918197ms |    192.168.1.99 | POST     /api/v1/match/create
Error #01: Error reading get5_web_avaliable response"

**Screenshots**
![image](https://user-images.githubusercontent.com/1731023/85213347-dad6ed80-b322-11ea-96b7-9c3e95f83d08.png)
![image](https://user-images.githubusercontent.com/1731023/85213358-ea563680-b322-11ea-8640-8f324f97e37c.png)

**Desktop (please complete the following information):**
 - Server OS: Centos 8.2.2004
 - Go version: 1.13.4
 - Browser: Chrome
 - Browser Version: 83.0.4103.106

**Comment by FlowingSPDG** [comment]
Thanks for the report! are you using latest build(https://github.com/FlowingSPDG/get5-web-go/releases/tag/v0.1.2-rconfix) ?
actually I committed a lot of changes after v0.1.2 so I can't look into it now.
perhaps you may disable SRCDS logs(`log off`) to suppress logs and let API parse correctly.

**Comment by sanegaming** [comment]
Thanks for the reply!

> Thanks for the report! are you using latest build(https://github.com/FlowingSPDG/get5-web-go/releases/tag/v0.1.2-rconfix) ?
I am using the latest 0.1.2-rconfix.
> actually I committed a lot of changes after v0.1.2 so I can't look into it now.
> perhaps you may disable SRCDS logs(`log off`) to suppress logs and let API parse correctly.
 in which config file is this value, I can't seem to find it?

**Comment by FlowingSPDG** [comment]
Will be fixed on v0.2.0.
