### ISSUE TITLE
[BUG] Error #01: JSON Format invalid when adding a server

### ISSUE THREAD

**Issue by tydaytygx** [FlowingSPDG/get5loader#183]
Bug of Add a server.
The server-side plugins are available(testing with get5_web_avaliable)
and sql is good to go.
The panel I could log in but adding the server POST 400 bad request?
```
Web
POSThttp://localhost:8080/api/v1/server/create

Backend
Error #01: JSON Format invalid
```
Did I miss some config?

Using golang1.16.2

**Comment by FlowingSPDG** [comment]
I think this bug is related to https://github.com/FlowingSPDG/get5-web-go/issues/175 .
If you're using SRCDS with logging enabled(``log on``), it might break JSON parsing.
I'm still working on how to fix it though, you can disable logging to add it correctly. However, you might need to disable logging whore time using get5-web-go.

**Comment by tydaytygx** [comment]
> 
> 
> I think this bug is related to #175 .
> If you're using SRCDS with logging enabled(`log on`), it might break JSON parsing.
> I'm still working on how to fix it though, you can disable logging to add it correctly. However, you might need to disable logging whore time using get5-web-go.

Hey, thanks for the apply! I shutdown all my srcds but still get the same issue, did I misunderstand the ```disable logging```?

**Comment by tydaytygx** [comment]
> 
> 
> I think this bug is related to #175 .
> If you're using SRCDS with logging enabled(`log on`), it might break JSON parsing.
> I'm still working on how to fix it though, you can disable logging to add it correctly. However, you might need to disable logging whore time using get5-web-go.

Well, the web may have some issue, but I managed to add server through sql editor, thanks for your apply!
