### ISSUE TITLE
Change repository name to get5loader

### ISSUE THREAD

**Issue by FlowingSPDG** [FlowingSPDG/get5loader#258]
Current repository name (get5-web-go) does not seem right since I am going to develop get5-web uncompatible system.
maybe take get5-web name or G5, Go5 or got5-web?

**Comment by xe1os** [comment]
> Current repository name (get5-web-go) does not seem right since I am going to develop get5-web uncompatible system. maybe take get5-web name or G5, Go5 or got5-web?

Hi!! got5-web sounds good.. :)

**Comment by FlowingSPDG** [comment]
Maybe got5-manager? Since got5 itself works on web.
Maybe I can integrate got5 into this repository.
